In [14]:
import pandas as pd

data = {
    '대여소': ['강남', '강남', '홍대', '홍대', '잠실', '잠실'],
    '이용자수': [120, 150, 80, 90, 200, 180],
    '대여시간': [30, 45, 20, 25, 60, 55],
    '이용일자': ['2024-01-01', '2024-01-02', '2024-01-01', '2024-01-02', '2024-01-01', '2024-01-02']
}

df = pd.DataFrame(data)


# 상위 3개 데이터 출력
# df.head(3) 
# df.info()
# 조건 필터
# df[df['이용자수'] >= 100]
# df.sort_values(by='대여시간', ascending=True)
# asc의 경우 생략해도 디폴트
# 내림차순 정렬 (by="", ascending=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   대여소     6 non-null      object
 1   이용자수    6 non-null      int64
 2   대여시간    6 non-null      int64
 3   이용일자    6 non-null      object
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

  대여소  이용자수  대여시간        이용일자
2  홍대    80    20  2024-01-01
3  홍대    90    25  2024-01-02
0  강남   120    30  2024-01-01
1  강남   150    45  2024-01-02
5  잠실   180    55  2024-01-02
4  잠실   200    60  2024-01-01

In [15]:
df['총이용량']=df['이용자수']*df['대여시간']
df

  대여소  이용자수  대여시간        이용일자   총이용량
0  강남   120    30  2024-01-01   3600
1  강남   150    45  2024-01-02   6750
2  홍대    80    20  2024-01-01   1600
3  홍대    90    25  2024-01-02   2250
4  잠실   200    60  2024-01-01  12000
5  잠실   180    55  2024-01-02   9900

In [22]:
# Data자료를 이용해 대여소별 총이용자수를 구한 후 
# 이용자수 많은 순으로 정렬하여 출력하시오
df.groupby('대여소')['이용자수'].sum().sort_values(ascending=False)

대여소
잠실    380
강남    270
홍대    170
Name: 이용자수, dtype: int64

In [25]:
# Data자료를 이용해 이용자수가 100 이상인
# 데이터만 추출하여 대여소별 평균대여시간 구하여 출력하시오
result = df[df['이용자수'] >= 100]
result.groupby('대여소')['대여시간'].mean()

대여소
강남    37.5
잠실    57.5
Name: 대여시간, dtype: float64

In [44]:
# Data자료를 이용해 대여소별 "총이용량" 합계 구하기
print("대여소별 총이용량 합계")
print(df.groupby('대여소')['총이용량'].sum())

대여소별 총이용량 합계
대여소
강남    10350
잠실    21900
홍대     3850
Name: 총이용량, dtype: int64

In [46]:
# 가장 바쁜 날짜 찾기.
busyDate = df.groupby('이용일자')['이용자수'].sum().sort_values(ascending=False)
print(busyDate)
print("가장 바쁜 날짜", busyDate.index[0])

이용일자
2024-01-02    420
2024-01-01    400
Name: 이용자수, dtype: int64
가장 바쁜 날짜 2024-01-02

In [47]:
# 이용자수 평균이 가장 높은 대여소 찾기.
line = df.groupby('대여소')['이용자수'].mean().sort_values(ascending=False)
print(line)
print(f"평균 이용자수 가장 높은 대여소: {line.index[0]}")

대여소
잠실    190.0
강남    135.0
홍대     85.0
Name: 이용자수, dtype: float64
평균 이용자수 가장 높은 대여소: 잠실