In [1]:
pip install bs4

Collecting bs4
  Downloading bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\lib\site-packages (from bs4) (4.13.5)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (4.15.0)
Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Installing collected packages: bs4
Successfully installed bs4-0.0.2
Note: you may need to restart the kernel to use updated packages.

In [2]:
from bs4 import BeautifulSoup

In [7]:
# 파일 읽기
with open('greenData/member_data.xml', 'r', encoding='utf-8-sig') as f:
    # 파싱
    soup = BeautifulSoup(f,'xml')
# 데이터 추출
members = soup.select('member')

for m in members:
    name = m.select_one('name').text
    age = m.select_one('age').text
    city = m.select_one('city').text
    print(f"이름: {name}, 나이: {age}, 도시: {city}")

이름: 김철수, 나이: 25, 도시: 서울
이름: 이영희, 나이: 30, 도시: 부산
이름: 박민수, 나이: 22, 도시: 대전

In [11]:
import json # anaconda에서 받아왔을것, 그러나 확인되지 않는다면 import할것
# json.loads() : JSON -> 파이썬 Dictionary
# json.dumps() : 파이썬 Dictionary -> JSON

# JSON -> Dict
json_str = '{"name":"Alice", "role":"admin", "level":5}'
data = json.loads(json_str)
print(data['name'], type(data))

Alice <class 'dict'>

In [14]:
# Dict -> JSON
user_dict = {"id":7, "status":"online"}
data=json.dumps(user_dict, indent=4) # indent: 들여쓰기
print(data)

{
    "id": 7,
    "status": "online"
}

In [34]:
# pandas: 테이블형 데이터를 다룰 수 있는 다양한 기능을 가진 라이브러리
# pandas의 dataType:
    # object - str, int 등 혼합
    # int64 - 정수
    # float64 - 부동소숫점
    # bool - boolean
    # datetime - 날짜/시간
    # timedelta - 두개의 datatime64간의 차이
# raw data: 정제되지 않은 기본데이터를 의미함
# import pandas as pd
# 데이터를 다루는 2가지 방식
    # Series: 1차원(행 or 열 하나)
    # DataFrame: 2차원(테이블)
import pandas as pd
# pd.함수명 호출해서 사용한다.
# index는 행의 label 이며, 지정하지 않으면 0부터 자동 생성
# dtype: int64
seriesData = pd.Series([70, 60, 90], index=['국어','영어','수학'])
seriesData.index=['미술','과학','사회']
seriesData
# 삭제
# del seriesData['미술']
seriesData
# dtype: object
seriesData2 = pd.Series(['A','B','C','D'])
seriesData2
# int -> float 명령어
seriesData.astype('float')
# bool
seriesData3 = pd.Series([True,False,True])
seriesData3

0     True
1    False
2     True
dtype: bool

In [62]:
# 데이터프레임은 테이블형(2차원) 데이터이며, 
# 데이터분석/머신러닝에서 데이터처리를 위해 주로사용됨
dfData = pd.DataFrame({
    # "년도":[2024,2025,2026],
    "미국":[4.1,3.2,2.6],
    "한국":[2.5,3.0,2.8],
    "중국":[0.8,1.0,1.2]},
    index=[2024,2025,2026]
)
dfData
# dfData.index=['A','B','C'] # 행(row,index) 수정
# dfData.columns = [2022,2024,2026] # 열(columns) 수정
dfData.values
# dfData.set_index('년도')
dfData.index.name = '년도'
dfData
# .loc[값] : index 를 통해서 값을 찾음
# dfData.loc[2026]
# .iloc[번호] : 인덱스 번호를 통해서값을찾음(0부터시작)
# dfData.iloc[0]
# type(dfData['미국'])
# print(dfData['미국'])

년도
2024    4.1
2025    3.2
2026    2.6
Name: 미국, dtype: float64

In [63]:
# print(dfData['한국'][2025])

3.0

In [65]:
# print(dfData.loc[2026]['한국'])

2.8

In [86]:
dfData['일본'] = [0.5,0.8,1.3]
dfData

# dfData

       미국   한국   중국   일본
년도
2024  4.1  2.5  0.8  0.5
2025  3.2  3.0  1.0  0.8
2026  2.6  2.8  1.2  1.3

In [84]:
# 행(row) 삭제: 
dfData.drop([2024])

       미국   한국   중국   일본
년도
2025  3.2  3.0  1.0  0.8
2026  2.6  2.8  1.2  1.3

In [87]:
del dfData['일본']
dfData

       미국   한국   중국
년도
2024  4.1  2.5  0.8
2025  3.2  3.0  1.0
2026  2.6  2.8  1.2